In [2]:
import pandas as pd

In [3]:
info={
    "name":["Abdullah","Mubasher","Hussain"],
    "CGPA":[9.4,9.5,9.9]
}
df=pd.DataFrame(info)
print(df)

       name  CGPA
0  Abdullah   9.4
1  Mubasher   9.5
2   Hussain   9.9

In [4]:
df

       name  CGPA
0  Abdullah   9.4
1  Mubasher   9.5
2   Hussain   9.9

In [6]:
s=pd.Series([1,2,3,4,5])
print(s)
print(type(s))
print(s[0])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1

In [8]:
s1=pd.Series([1,2,3,4,5,6,7], index=["o","t","th","f","fi","s","se"])

In [9]:
print(s1)

o     1
t     2
th    3
f     4
fi    5
s     6
se    7
dtype: int64

In [11]:
print(s1.index)

Index(['o', 't', 'th', 'f', 'fi', 's', 'se'], dtype='object')

In [14]:
drop_s1=s1.drop("se")
print(s1)
print(drop_s1)

o     1
t     2
th    3
f     4
fi    5
s     6
se    7
dtype: int64
o     1
t     2
th    3
f     4
fi    5
s     6
dtype: int64

In [15]:
s1+drop_s1

f      8.0
fi    10.0
o      2.0
s     12.0
se     NaN
t      4.0
th     6.0
dtype: float64

In [17]:
df1=pd.DataFrame({
    "name":["Abdullah","Bhatti","Hussain"],
    "age":[1,18,21],
    "CGPA":[9,3,9.9]
})
print(df1)
df1

       name  age  CGPA
0  Abdullah    1   9.0
1    Bhatti   18   3.0
2   Hussain   21   9.9

       name  age  CGPA
0  Abdullah    1   9.0
1    Bhatti   18   3.0
2   Hussain   21   9.9

In [18]:
df2=pd.DataFrame([["Abdullah","12"],["Bhatti","34"],["Hussain","56"]],columns=["Name","Num"])
print(df2)
df2

       Name Num
0  Abdullah  12
1    Bhatti  34
2   Hussain  56

       Name Num
0  Abdullah  12
1    Bhatti  34
2   Hussain  56

In [20]:
data=pd.read_csv("employee_data.csv")
print(data)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [21]:
data.head()

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [22]:
data.tail()

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [24]:
data.sample()

   ID Name  Age Department  Salary
1   2  Bob   32         IT   72000

In [26]:
data.shape

(10, 5)

In [27]:
data.describe()

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [31]:
data.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [32]:
data.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64