In [1]:
import pandas as pd

In [2]:
info={
    "name":["Abdullah","Mubasher","Hussain"],
    "CGPA":[9.4,9.5,9.9]
}
df=pd.DataFrame(info)
print(df)

       name  CGPA
0  Abdullah   9.4
1  Mubasher   9.5
2   Hussain   9.9

In [3]:
df

       name  CGPA
0  Abdullah   9.4
1  Mubasher   9.5
2   Hussain   9.9

In [4]:
s=pd.Series([1,2,3,4,5])
print(s)
print(type(s))
print(s[0])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1

In [5]:
s1=pd.Series([1,2,3,4,5,6,7], index=["o","t","th","f","fi","s","se"])

In [6]:
print(s1)

o     1
t     2
th    3
f     4
fi    5
s     6
se    7
dtype: int64

In [7]:
print(s1.index)

Index(['o', 't', 'th', 'f', 'fi', 's', 'se'], dtype='object')

In [8]:
drop_s1=s1.drop("se")
print(s1)
print(drop_s1)

o     1
t     2
th    3
f     4
fi    5
s     6
se    7
dtype: int64
o     1
t     2
th    3
f     4
fi    5
s     6
dtype: int64

In [9]:
s1+drop_s1

f      8.0
fi    10.0
o      2.0
s     12.0
se     NaN
t      4.0
th     6.0
dtype: float64

In [10]:
df1=pd.DataFrame({
    "name":["Abdullah","Bhatti","Hussain"],
    "age":[1,18,21],
    "CGPA":[9,3,9.9]
})
print(df1)
df1

       name  age  CGPA
0  Abdullah    1   9.0
1    Bhatti   18   3.0
2   Hussain   21   9.9

       name  age  CGPA
0  Abdullah    1   9.0
1    Bhatti   18   3.0
2   Hussain   21   9.9

In [11]:
df2=pd.DataFrame([["Abdullah","12"],["Bhatti","34"],["Hussain","56"]],columns=["Name","Num"])
print(df2)
df2

       Name Num
0  Abdullah  12
1    Bhatti  34
2   Hussain  56

       Name Num
0  Abdullah  12
1    Bhatti  34
2   Hussain  56

In [12]:
data=pd.read_csv("employee_data.csv")
print(data)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [13]:
data.head()

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [14]:
data.tail()

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [16]:
data.sample()

   ID   Name  Age Department  Salary
6   7  Grace   41         HR   82000

In [17]:
data.shape

(10, 5)

In [18]:
data.describe()

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [19]:
data.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [20]:
data.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [21]:
air_data=pd.read_csv("globalAirQuality.csv")

In [22]:
print(air_data)

                        timestamp country      city  latitude  longitude  \
0      2025-11-04 18:25:17.554219      US  New York    40.713    -74.006
1      2025-11-04 19:25:17.554219      US  New York    40.713    -74.006
2      2025-11-04 20:25:17.554219      US  New York    40.713    -74.006
3      2025-11-04 21:25:17.554219      US  New York    40.713    -74.006
4      2025-11-04 22:25:17.554219      US  New York    40.713    -74.006
...                           ...     ...       ...       ...        ...
17995  2025-11-19 13:25:17.554219      CH    Zurich    47.377      8.542
17996  2025-11-19 14:25:17.554219      CH    Zurich    47.377      8.542
17997  2025-11-19 15:25:17.554219      CH    Zurich    47.377      8.542
17998  2025-11-19 16:25:17.554219      CH    Zurich    47.377      8.542
17999  2025-11-19 17:25:17.554219      CH    Zurich    47.377      8.542

         pm25     pm10     no2    so2      o3     co  aqi  temperature  \
0      50.295  108.938  27.998  6.539  52.568  1.096  108       18.504
1      32.083   63.043  36.120  4.021  43.536  1.075   90        5.838
2      42.250   82.553  26.935  9.538  23.320  0.977   84       31.833
3      30.403   79.951  63.536  7.609  31.369  0.230  158       23.140
4      21.083   66.423  38.997  6.919  45.615  1.085   97       13.632
...       ...      ...     ...    ...     ...    ...  ...          ...
17995  27.899   74.179  41.474  6.677  50.869  1.028  103        7.079
17996   2.950   47.988  42.235  2.821  35.551  0.644  105       28.734
17997  61.347   72.908  46.976  5.763  66.492  0.947  122       21.951
17998  40.722   95.152  32.957  5.524  53.193  0.868   95       24.042
17999  25.830   30.411  35.317  4.336  66.246  0.848   88        8.529

       humidity  wind_speed
0        70.168       3.725
1        80.088       8.969
2        62.783       9.650
3        89.153       8.956
4        76.499       4.017
...         ...         ...
17995    52.443       7.452
17996    85.678       4.496
17997    72.311       9.660
17998    31.880       2.642
17999    59.104       4.403

[18000 rows x 15 columns]

In [23]:
air_data

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [24]:
air_data.head()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [25]:
air_data.sample()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
8770,2025-11-10 04:25:17.554219,JP,Osaka,34.694,135.502,41.271,116.957,49.767,1.93,33.575,0.765,124,9.621,61.002,5.949

In [26]:
air_data.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [28]:
air_data["country"]

0        US
1        US
2        US
3        US
4        US
         ..
17995    CH
17996    CH
17997    CH
17998    CH
17999    CH
Name: country, Length: 18000, dtype: object

In [29]:
air_data.iloc[0:3]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650

In [32]:
air_data.iloc[3,2]

'New York'

In [33]:
air_data.loc[10:20,["city","aqi"]]

        city  aqi
10  New York   96
11  New York   99
12  New York  114
13  New York  124
14  New York  121
15  New York   91
16  New York  130
17  New York  127
18  New York   87
19  New York  151
20  New York  102

In [48]:
new_data=air_data[(air_data["aqi"]>100)&(air_data["temperature"]>30)][["city","aqi"]]
print(new_data)

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [51]:
new_data.iloc[0]

city    New York
aqi          155
Name: 6, dtype: object

In [63]:
air_data.query("aqi<25")[["city","aqi"]]

       city  aqi
960  London   16

In [65]:
df=pd.read_csv("raw_data.csv")

In [67]:
df.isnull()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [71]:
df.isnull().sum()

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [75]:
cleaned_data=df["age"].copy()
cleaned_data

0     29.0
1     29.0
2      NaN
3      NaN
4     34.0
5     27.0
6     45.0
7     38.0
8     29.0
9      NaN
10    31.0
Name: age, dtype: float64

In [76]:
mean=cleaned_data.mean()

In [77]:
cleaned_data.fillna(mean)

0     29.00
1     29.00
2     32.75
3     32.75
4     34.00
5     27.00
6     45.00
7     38.00
8     29.00
9     32.75
10    31.00
Name: age, dtype: float64

In [78]:
df.ffill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [79]:
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [80]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [81]:
df2=df.copy()

In [82]:
df2=df2.ffill()

In [85]:
df2[["name","gender"]].duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [86]:
df2=df2.drop_duplicates()

In [87]:
df2

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [88]:
df["country"].str.lower()

0        usa
1        usa
2     canada
3        usa
4      spain
5      china
6      india
7        NaN
8        usa
9     mexico
10       usa
Name: country, dtype: object

In [89]:
df["country"].str.contains("india", case=False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object